language: node_js
node_js:
- '6'
- '4'
after_script: make test-cov
env:
  matrix:
  - COVERALLS_SERVICE_NAME=travis-ci
  global:
    secure: sa3dK+Avi/dcFaUZ/8bquBCAe0nUQ/yVusvzw5joUpJpzrIJKlIxV86bLa58cJAZSNGNyl/ZcjUaejR4xKyjJuYuLsOqN9p3tAY24AgnSf1Tr8EH3ML0k8e0HdOtmbEo9Rn742XSxN0VcPoXgeJgM0vigTJ66iqav6sJ2DMPKDQ=
